# -*- coding: utf-8 -*-
# Generated by Django 1.11.27 on 2020-01-03 07:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sidebar',
            old_name='dispaly_type',
            new_name='display_type',
        ),
    ]
