# -*- coding: utf-8 -*-
# Generated by Django 1.11.27 on 2020-01-03 07:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Link',
            new_name='Comment',
        ),
    ]
